wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1670661830.482656
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.10.6
      5: 0.13.3
      8:
      - 3
      - 5
